FROM openjdk:17-jdk-alpine

# spring 사용자와 그룹 생성
RUN addgroup -S spring && adduser -S spring -G spring

# spring 사용자로 실행
USER spring:spring

# 애플리케이션 JAR 파일 경로 설정
ARG JAR_FILE=target/*.jar

# JAR 파일 복사
COPY ${JAR_FILE} app.jar

# 애플리케이션 실행
ENTRYPOINT ["java","-jar","/app.jar"]

# 5. 필요 포트 공개
EXPOSE 8443